window.words = [
    { word: "Apple", hint: "Red fruit that keeps doctors away" },
    { word: "Window", hint: "Glass pane in a wall" },
    { word: "Purple", hint: "Color mixing red and blue" },
    { word: "Planet", hint: "Celestial body orbiting a star" },
    { word: "Pencil", hint: "Writing tool with graphite core" },
    { word: "Summer", hint: "Hottest season of the year" },
    { word: "Coffee", hint: "Popular caffeinated beverage" },
    { word: "Fossil", hint: "Preserved remains in rock" },
    { word: "Eclipse", hint: "Celestial body obscuring another" },
    { word: "Dynamite", hint: "Explosive containing nitroglycerin" },
    { word: "Kangaroo", hint: "Hopping marsupial with pouch" },
    { word: "Gazelle", hint: "Swift African antelope" },
    { word: "Harmony", hint: "Pleasing musical combination" },
    { word: "Journal", hint: "Daily record or periodical" },
    { word: "Illusion", hint: "Deceptive appearance or belief" },
    { word: "Cinnamon", hint: "Fragrant brown spice" },
    { word: "Vortex", hint: "Spinning flow of fluid/energy" },
    { word: "Guitar", hint: "Six-string musical instrument" },
    { word: "Xylophone", hint: "Musical instrument with wooden bars" },
    { word: "Rabbit", hint: "Hopping animal with long ears" },
    { word: "Camera", hint: "Device for capturing photos" },
    { word: "Phone", hint: "Device for calling and texting" },
    { word: "Doctor", hint: "Medical professional" },
    { word: "Smile", hint: "Facial expression showing happiness" },
    { word: "Beach", hint: "Sandy shore by the ocean" },
    { word: "Chair", hint: "Four-legged furniture for sitting" },
    { word: "javascript", hint: "A popular programming language for web development" },
    { word: "algorithm", hint: "A step-by-step procedure to solve a problem" },
    { word: "variable", hint: "A container for storing data values" },
    { word: "function", hint: "A block of code designed to perform a particular task" },
    { word: "database", hint: "An organized collection of structured information" },
    { word: "html", hint: "The standard markup language for web pages" },
    { word: "css", hint: "Style sheet language used for describing presentation" },
    { word: "python", hint: "A high-level programming language known for its readability" },
    { word: "react", hint: "A JavaScript library for building user interfaces" },
    { word: "node", hint: "A JavaScript runtime built on Chrome's V8 JavaScript engine" }
];